# Generated by Django 4.1.3 on 2022-11-15 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=255)),
                ('number_of_items', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=40)),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=9999999999)),
                ('total_inclusive_tax', models.DecimalField(decimal_places=2, max_digits=9999999999)),
                ('total_exclusive_tax', models.DecimalField(decimal_places=2, max_digits=9999999999)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('taxpayer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efd.taxpayer')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=255)),
                ('tin', models.CharField(max_length=100)),
                ('taxpayer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efd.taxpayer')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('taxpayer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efd.taxpayer')),
            ],
        ),
    ]
